### ISSUE TITLE
Add possibility to provide TestRail credentials also as ENV variables

### ISSUE THREAD

**Issue by viktorgogulenko** [Slobo989/jasmine-2-testrail#4]
It would be great to be able to provide TestRail credentials not only using 'testrail-credentails.json', but also using environment variables (which will be really good if we are running tests in CI).

**Comment by Slobo989** [comment]
We did provided new feature for environment variables.

## Example - **.env**
This file needs to be created in the root directory of the project.
<br> It must contain the URL of your TestRail, username (email address) and password (or API key).
<br> This file needs to have all 3 parameters correctly filled.
```javascript
NETWORK_URL = https://<YourProjectURL>.testrail.io
USERNAME = email address
PASSWORD = password or API key
```

**Comment by viktorgogulenko** [comment]
It failed for me as soon as I've updated a version of 'jasmine-2-testrail':

> [11:32:51] E/configParser - Error code: 105
[11:32:51] E/configParser - Error message: failed loading configuration file protractor.conf.js
[11:32:51] E/configParser - Error: ENOENT: no such file or directory, open '../.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (./node_modules/jasmine-2-testrail/jasmine-2-testrail.js:7:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

I've added .env file to the root folder, but it failed again. A soon as I've tried to update this string in 'jasmine-2-testrail.js' file:
`const envFile = fs.readFileSync('../.env')`
to
`const envFile = fs.readFileSync('./.env')`
as seems it tries to find env-file in parent directory (my protractor.conf.js is also in root directory)

Could you please look into this issue?

**Comment by zeljkosimic95** [comment]
The issue should now be resolved. I also updated the readme to say the .env file should be placed in the same directory as the conf file.
Please let us know if you run into any more issues.

**Comment by viktorgogulenko** [comment]
I've found another issue - seems .env file is not optional, but required to be in place. If there are no such file - job fails completely. Seems it should be optional instead (if we don't want to provide it and to use json-file with credentials).

**Comment by zeljkosimic95** [comment]
It's not optional, we've switched to using only an .env file, as that is a more common practice with things like these. It should be functionally identical to a json file.

**Comment by annbr204** [comment]
I have my tests in Typescript and I have placed my .env file in the same directory as my conf.ts file. I am getting the error
`You don't have an .env file!
 { Error: ENOENT: no such file or directory, open '.env'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/node_modules/jasmine-2-testrail/jasmine-2-testrail.js:9:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }`
